apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: managed-clusters
  namespace: etherpad
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      env: managed
