apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-etherpad
  namespace: rhacm-policies
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-etherpad
        spec:
          severity: medium
          namespaceSelector:
            include:
            - etherpad
          object-templates:
            - complianceType: inform
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: etherpad-secret
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-etherpad
  namespace: rhacm-policies
placementRef:
  name: managed-clusters
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-etherpad
  kind: Policy
  apiGroup: policy.open-cluster-management.io
